version: '3.8'

services:
  coffeeshopapi:
    image: ${DOCKER_REGISTRY-}coffeeshopapi
    build:
      context: CoffeeShopApi
      dockerfile: Dockerfile
    depends_on:
        postgres:
            condition: service_healthy
    ports:
        - "8080:8080"
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CoffeeShop
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL","pg_isready -U postgres -d CoffeeShop"]
        interval: 5s
        timeout: 5s
        retries: 5
volumes:
    postgres_data:
    